### ISSUE TITLE
Why run initialize before restore?

### ISSUE THREAD

**Issue by AnlanSun** [cameronfabbri/LSGANs-Tensorflow#1]
Anyway thanks for this good job. It does help me a lot

**Comment by cameronfabbri** [comment]
I believe you need to have a session running before you can restore a model. I followed Tensorflow's guide to exporting and importing models [here.](https://www.tensorflow.org/programmers_guide/meta_graph) You'll notice that they restore inside of `with tf.Session as sess:`
